sygnalya: sygnaly_a.c
	gcc sygnaly_a.c -o sygnalya

sygnalyb: sygnaly_b.c
	gcc sygnaly_b.c -o sygnalyb

sygnalyc: sygnaly_c.c
	gcc sygnaly_c.c -o sygnalyc
	
all: sygnaly_a.c sygnaly_b.c sygnaly_c.c
	gcc sygnaly_a.c -o sygnalya
	gcc sygnaly_b.c -o sygnalyb
	gcc sygnaly_c.c -o sygnalyc
