potoki5b_kons: potoki5b_kons.c
	gcc potoki5b_kons.c -o potoki5b_kons
	
potoki5b_prod: potoki5b_prod.c
	gcc potoki5b_prod.c -o potoki5b_prod

all: potoki5b_kons potoki5b_prod

runkons: potoki5b_kons
	./potoki5b_kons
	
runprod: potoki5b_prod
	./potoki5b_prod
